version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CMDB_NEO4J_HOST=neo4j
      - CMDB_NEO4J_PORT=7687
      - CMDB_NEO4J_USER=neo4j
      - CMDB_NEO4J_PASSWORD=dementor_cmdb
      - CMDB_NEO4J_DATABASE=neo4j
      - CMDB_API_KEYS=admin:admin-api-key:read,write,admin;user:user-api-key:read
    depends_on:
      - neo4j
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  neo4j:
    image: neo4j:5.8.0-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./base-init.sh:/var/lib/neo4j/import/base-init.sh
    environment:
      - NEO4J_AUTH=neo4j/dementor_cmdb
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "dementor_cmdb", "RETURN 1;"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import: